services:
  mongo:
    image: mongo:7
    container_name: abramson-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: abramson_local_work

volumes:
  mongo_data:
